
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BOOLEAN CHAR COLON COMMA COMMENT CTEB CTEC CTEF CTEI CTES DIVIDE ELSE EQUALS FALSE FLOAT GREATER ID IF INT LBRACE LBRACK LESS LPAREN MAIN MINUS NOTEQUAL PLUS PRINT PROGRAM RBRACE RBRACK RETURN RPAREN SEMICOLON STRING THEN TIMES TRUE VARIABLE WHILE\n    program : PROGRAM ID SEMICOLON var_declaration\n    \n    var_declaration : VARIABLE simple_type variables SEMICOLON\n    \n    variables : variables COMMA variable\n            | variable\n    \n    variable : ID\n            | ID LBRACK expression RBRACK\n            | ID LBRACK expression RBRACK LBRACK expression RBRACK\n    \n    simple_type : INT\n                | FLOAT\n                | CHAR\n                | STRING\n                | BOOLEAN\n    \n    expression : term \n                | term PLUS term\n                | term MINUS term\n    \n    term : factor \n        | factor TIMES factor\n        | factor DIVIDE factor\n    \n    factor : variable\n        | cte\n        | LPAREN expression RPAREN \n    \n    cte : CTEI\n        | CTEF\n        | CTEC\n        | CTES\n        | CTEB\n    '
    
_lr_action_items = {'PROGRAM':([0,],[2,]),'$end':([1,5,16,],[0,-1,-2,]),'ID':([2,7,8,9,10,11,12,17,18,25,32,33,34,35,37,],[3,15,-8,-9,-10,-11,-12,15,15,15,15,15,15,15,15,]),'SEMICOLON':([3,13,14,15,19,31,44,],[4,16,-4,-5,-3,-6,-7,]),'VARIABLE':([4,],[6,]),'INT':([6,],[8,]),'FLOAT':([6,],[9,]),'CHAR':([6,],[10,]),'STRING':([6,],[11,]),'BOOLEAN':([6,],[12,]),'COMMA':([13,14,15,19,31,44,],[17,-4,-5,-3,-6,-7,]),'TIMES':([15,22,23,24,26,27,28,29,30,31,42,44,],[-5,34,-19,-20,-22,-23,-24,-25,-26,-6,-21,-7,]),'DIVIDE':([15,22,23,24,26,27,28,29,30,31,42,44,],[-5,35,-19,-20,-22,-23,-24,-25,-26,-6,-21,-7,]),'PLUS':([15,21,22,23,24,26,27,28,29,30,31,40,41,42,44,],[-5,32,-16,-19,-20,-22,-23,-24,-25,-26,-6,-17,-18,-21,-7,]),'MINUS':([15,21,22,23,24,26,27,28,29,30,31,40,41,42,44,],[-5,33,-16,-19,-20,-22,-23,-24,-25,-26,-6,-17,-18,-21,-7,]),'RBRACK':([15,20,21,22,23,24,26,27,28,29,30,31,38,39,40,41,42,43,44,],[-5,31,-13,-16,-19,-20,-22,-23,-24,-25,-26,-6,-14,-15,-17,-18,-21,44,-7,]),'RPAREN':([15,21,22,23,24,26,27,28,29,30,31,36,38,39,40,41,42,44,],[-5,-13,-16,-19,-20,-22,-23,-24,-25,-26,-6,42,-14,-15,-17,-18,-21,-7,]),'LBRACK':([15,31,],[18,37,]),'LPAREN':([18,25,32,33,34,35,37,],[25,25,25,25,25,25,25,]),'CTEI':([18,25,32,33,34,35,37,],[26,26,26,26,26,26,26,]),'CTEF':([18,25,32,33,34,35,37,],[27,27,27,27,27,27,27,]),'CTEC':([18,25,32,33,34,35,37,],[28,28,28,28,28,28,28,]),'CTES':([18,25,32,33,34,35,37,],[29,29,29,29,29,29,29,]),'CTEB':([18,25,32,33,34,35,37,],[30,30,30,30,30,30,30,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'var_declaration':([4,],[5,]),'simple_type':([6,],[7,]),'variables':([7,],[13,]),'variable':([7,17,18,25,32,33,34,35,37,],[14,19,23,23,23,23,23,23,23,]),'expression':([18,25,37,],[20,36,43,]),'term':([18,25,32,33,37,],[21,21,38,39,21,]),'factor':([18,25,32,33,34,35,37,],[22,22,22,22,40,41,22,]),'cte':([18,25,32,33,34,35,37,],[24,24,24,24,24,24,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> PROGRAM ID SEMICOLON var_declaration','program',4,'p_program','parser_1.py',6),
  ('var_declaration -> VARIABLE simple_type variables SEMICOLON','var_declaration',4,'p_var_declaration','parser_1.py',12),
  ('variables -> variables COMMA variable','variables',3,'p_variables','parser_1.py',19),
  ('variables -> variable','variables',1,'p_variables','parser_1.py',20),
  ('variable -> ID','variable',1,'p_variable','parser_1.py',27),
  ('variable -> ID LBRACK expression RBRACK','variable',4,'p_variable','parser_1.py',28),
  ('variable -> ID LBRACK expression RBRACK LBRACK expression RBRACK','variable',7,'p_variable','parser_1.py',29),
  ('simple_type -> INT','simple_type',1,'p_simple_type','parser_1.py',36),
  ('simple_type -> FLOAT','simple_type',1,'p_simple_type','parser_1.py',37),
  ('simple_type -> CHAR','simple_type',1,'p_simple_type','parser_1.py',38),
  ('simple_type -> STRING','simple_type',1,'p_simple_type','parser_1.py',39),
  ('simple_type -> BOOLEAN','simple_type',1,'p_simple_type','parser_1.py',40),
  ('expression -> term','expression',1,'p_expression','parser_1.py',47),
  ('expression -> term PLUS term','expression',3,'p_expression','parser_1.py',48),
  ('expression -> term MINUS term','expression',3,'p_expression','parser_1.py',49),
  ('term -> factor','term',1,'p_term','parser_1.py',56),
  ('term -> factor TIMES factor','term',3,'p_term','parser_1.py',57),
  ('term -> factor DIVIDE factor','term',3,'p_term','parser_1.py',58),
  ('factor -> variable','factor',1,'p_factor','parser_1.py',65),
  ('factor -> cte','factor',1,'p_factor','parser_1.py',66),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor','parser_1.py',67),
  ('cte -> CTEI','cte',1,'p_cte','parser_1.py',74),
  ('cte -> CTEF','cte',1,'p_cte','parser_1.py',75),
  ('cte -> CTEC','cte',1,'p_cte','parser_1.py',76),
  ('cte -> CTES','cte',1,'p_cte','parser_1.py',77),
  ('cte -> CTEB','cte',1,'p_cte','parser_1.py',78),
]
